### PR TITLE
Fix missing public deps

### PR DESCRIPTION
**Pull request by Mosnar**
There were some issues with the craft boilerplate. Specifically, the default db host was wrong and the public folder was not getting the latest resources from the craft distribution. I've added some logic to pull down the latest craft public folder and update the craft path in the index.php to fit with our project structure.

### CODE REVIEW

**Comment by themccallister** [comment]
Awesome for fixing the bug! 

Lets have a discussion on the public index.php. The dotenv loading is required if the environment does not support setting env vars. This is most notable on products like MAMP... Heroku and Docker allow environment variables by default. However, in situations where we use something like ServerPilot, we do not have an easy way to set environment variables... So PHP DotEnv comes into play.

Check out this article, https://mattstauffer.co/blog/environment-specific-configuration-for-craftcms-using-phpdotenv, and lets discuss some more.

**Comment by Mosnar** [comment]
@themccallister Shoot, you're so right! I didn't realize our index.php file was customized. I'm gonna mull this over and see if we can't come up with another solution. I'd really like to get all of the craft files back under their VCS, but that might be pipe dream.

**Comment by Mosnar** [comment]
also, this: `define('CRAFT_TEMPLATES_PATH', "../resources/templates");`

**Comment by themccallister** [comment]
When you say "under their VCS" do you mean the files that come from the installer/download?

**Comment by Mosnar** [comment]
Yep, that's exactly what I mean

**Pull request closed without merging**
